name: carfare
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  animated_text_kit: any
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  modal_progress_hud: ^0.1.3
  time_machine: ^0.9.16
  awesome_notifications: any
  flutter_secure_storage: ^4.2.1
  shared_preferences: ^2.0.7
  fluttertoast: ^8.0.8
  image_picker: ^0.7.2
  camera: ^0.8.1
  google_ml_kit: any
  flutter_stripe: any
  http: any
  pay: ^1.0.6
  flutter_animated_dialog: any
  intl: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/

